### ISSUE TITLE
Telescope:WhenRegionLoads(callback)

### ISSUE THREAD

**Issue by SuperRuper1209** [iimurpyh/pilot-lua#11]
method you pass a callback function.
example of usage:

function callback(regData)

end
local tele = GetPartFromPort(1, "Telescope")
tele:WhenRegionLoads(callback)

Tele:Configre({....})
Tele:Configre({....})

-- callback is called twice

**Comment by SuperRuper1209** [comment]
![image](https://user-images.githubusercontent.com/77413429/197419061-5f10f66d-5546-4e64-b493-20b50d508c13.png)
proof

**Comment by hail12pink** [comment]
ok

**Comment by hail12pink** [comment]
https://github.com/iimurpyh/pilot-lua/wiki/Telescope#void-telescopewhenregionloadscallback
