### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by Darkstepan** [iimurpyh/pilot-lua#23]
I wasn't able to find documentation for these things:
- Container
- Part.GUID
- Microcontroller:Communicate()
- Button
- Assembler
- Constructor

Confusing:
StarMap documentation doesn't specify how coordinates are represented
https://github.com/iimurpyh/pilot-lua/wiki/StarMap
>```lua
>for k, v in StarMap:GetBodies() do
>  print(k, v) --> v is coordinates, k is null.
>end
>```

Other issues:
from issue #21
- Container - probably enough to duplicate the Bin page and replace "Bin" with "Container"
- Faucet - probably enough to duplicate the Dispenser page and replace "Dispenser" with "Faucet"

from issue #20 
- Light:SetColor(Color3)

from issue #3
- Part:GetEvents()
- Part:GetMethods()
- Part:GetConfigurables()
- Part.Position
- Part.CFrame

**Comment by Erex147** [comment]
> for k, v in StarMap:GetBodies() do
>  print(k, v) --> v is coordinates, k is null.
> end

I don't think this works becuz there's no pairs or ipairs mentioned

**Comment by iimurpyh** [comment]
https://github.com/iimurpyh/pilot-lua/wiki/Part#string-partguid
https://github.com/iimurpyh/pilot-lua/wiki/Container
https://github.com/iimurpyh/pilot-lua/wiki/Faucet
https://github.com/iimurpyh/pilot-lua/wiki/Microcontroller-Globals#void-communicate (also added SandboxID and SandboxRunID globals)
https://github.com/iimurpyh/pilot-lua/wiki/Button
https://github.com/iimurpyh/pilot-lua/wiki/Part#vector3-partposition
https://github.com/iimurpyh/pilot-lua/wiki/Part#cframe-partcframe
https://github.com/iimurpyh/pilot-lua/wiki/Light#void-lightsetcolorcolor3-color
https://github.com/iimurpyh/pilot-lua/wiki/Coordinate-Strings (Now linked to by Telescope and StarMap)

Assembler, Constructor, Part:GetEvents(), Part:GetMethods(), and Part:GetConfigurables() are not implemented in Stable. I will document them when they are.
