### ISSUE TITLE
ScreenObject:Clone()

### ISSUE THREAD

**Issue by dorpg9** [iimurpyh/pilot-lua#24]
* [`ScreenObject ScreenObject:Clone()`](#void-screenobjectclone)

___

## `ScreenObject ScreenObject:Clone()`

> Create a copy of the ScreenObject and all its children, ignoring ScreenObjects that are not [Archivable](https://create.roblox.com/docs/reference/engine/classes/Instance#Archivable).

**Comment by iimurpyh** [comment]
[done](https://github.com/iimurpyh/pilot-lua/wiki/ScreenObject#screenobject-screenobjectclone)
