### ISSUE TITLE
Fix the capitalization of Roblox in the repo desc

### ISSUE THREAD

**Issue by dxluca** [iimurpyh/pilot-lua#26]
The desc of this repository says "Documentation for the programming language of **ROBLOX** game Waste of Space". This spelling is outdated. The proper capitalization is "Roblox".

"©2024 **Roblox** Corporation. **Roblox**, the **Roblox** logo [...]" (https://www.roblox.com/home)

**Comment by RocketsSpace** [comment]
I recommend that you use the tags provided when creating an issue thread.

**Comment by dxluca** [comment]
> I recommend that you use the tags provided when creating an issue thread.

Well, I would have. As you can see when creating an issue, you can't add them by yourself. Also, none of the labels precisely describe the issue, "inaccurate page" would be misleading.

**Comment by iimurpyh** [comment]
yeah ok
