### ISSUE TITLE
Keyboard KeyPressed event parameters

### ISSUE THREAD

**Issue by TK-A369** [iimurpyh/pilot-lua#5]
This wiki says that parameters of `KeyPressed` event are: `KeyCode key, string Player` , but I discovered that those parameters are: `key: Enum.KeyCode, keyStr: string, userInputState: Enum.UserInputState, player: string` . And `userInputState` is always `Enum.UserInputState.End` .
Description of this event should be corrected.

**Comment by TK-A369** [comment]
`keyStr` is a stringified `key`, so in example `a`, `b`, `A`. Holding shift makes capital letter. But on non-printable characters such as Return/Enter or Backspace it's empty string.

**Comment by iimurpyh** [comment]
Fixed. What a weird way to do the event arguments, two of them are useless LOL

**Comment by hail12pink** [comment]
what this is an absolutely horrendous function
