### ISSUE TITLE
Change Modem.MessageSent to Modem.MessageReceived

### ISSUE THREAD

**Issue by fl215** [iimurpyh/pilot-lua#6]
`Modem.MessageReceived` literally means what it's in the description. `Modem.MessageSent` is when this modem sends a message. (Now that can be useful in a few ways so adding `Modem.MessageSent` to the module would be cool).

**Comment by iimurpyh** [comment]
This wiki is unofficial, suggestions for changes to the actual language should be put in the #suggestions category in the discord
